### ISSUE TITLE
Добавить ссылку на демо страницы

### ISSUE THREAD

**Issue by tsvetkovamaria** [keylink/exam4#9]
Для облегчения просмотра вашей страницы, было бы здорово добавить сылку на уже свертсанную страницу (демо) в файл readme.md вашего репозитория. Тогда любой человек сможет зайтив репо, кликнуть на ссылку и посмотреть готовую работу в браузере, не клонируя репо локально. 

Можно добавить себе демо версию страницы через github pages

Ваш файл ридми должен содержать описание вашего проекта, а не маркдауна или какого-то стороннего проекта.

**Comment by keylink** [comment]
Добавил в "Read me" ссылку на страницу с проектом http://c2n.me/3ICp9gx
